github debug

diff --git a/.github/workflows/run-connected-checks.yml b/.github/workflows/run-connected-checks.yml
--- a/.github/workflows/run-connected-checks.yml
+++ b/.github/workflows/run-connected-checks.yml
@@ -31,17 +31,19 @@ jobs:
             touch app/emulator.log                    # create log file
             chmod 777 app/emulator.log                # allow writing to log file
             adb logcat >> app/emulator.log &          # pipe all logcat messages into log file as a background process
-            ./gradlew connectedCheck 2>&1      # supress errors didn't work
-            # store the exit code from the test run
-            # bash uses capital letters, zsh uses lowecase:
-            exitcode=$?
-            echo "exitcode became: $exitcode"
             
-            # copy any screenshots if exists, silencing the error when there are no screenshots
-            adb pull /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures app 2>&1
-            
-            # exit with the code from the testrun
-            exit ${exitcode}
+            #gradleResult=$(./gradlew connectedCheck 2>&1)      # supress errors didn't work
+            if ./gradlew connectedCheck; then      
+                echo "Gradle task succeeded"
+            else 
+                exitcode=$?
+                echo "Gradle task failed"
+                # copy any screenshots if exists, silencing the error when there are no screenshots
+                adb pull /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures app 2>&1
+                
+                # exit with the code from the testrun
+                exit ${exitcode}
+            fi
           
       - name: Upload Failing Test Report Log
         if: ${{ always() }}
