Github one-liner

diff --git a/.github/workflows/run-connected-checks.yml b/.github/workflows/run-connected-checks.yml
--- a/.github/workflows/run-connected-checks.yml
+++ b/.github/workflows/run-connected-checks.yml
@@ -33,17 +33,7 @@ jobs:
             adb logcat >> app/emulator.log &          # pipe all logcat messages into log file as a background process
             
             #gradleResult=$(./gradlew connectedCheck 2>&1)      # supress errors didn't work
-            if ./gradlew connectedCheck; then      
-                echo "Gradle task succeeded"
-            else 
-                exitcode=$?
-                echo "Gradle task failed"
-                # copy any screenshots if exists, silencing the error when there are no screenshots
-                adb pull /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures app 2>&1
-                
-                # exit with the code from the testrun
-                exit ${exitcode}
-            fi
+            if ./gradlew connectedCheck; then; echo "Gradle task succeeded"; else  ;exitcode=$? ;echo "Gradle task failed" ;adb pull /sdcard/Android/data/com.swedbankpay.mobilesdk.merchantbackend.test/files/Pictures app 2>&1 ;exit ${exitcode}; fi
           
       - name: Upload Failing Test Report Log
         if: ${{ always() }}
